language: php
os: linux
dist: xenial
services:
  - mysql
addons:
  chrome: stable

php:
  - 7.3

mysql:
  database: drupal
  username: root
  encoding: utf8

env:
  COMPOSER_HOME=$HOME/.config/composer

cache:
  yarn: true
  directories:
     - $COMPOSER_HOME/cache
     - $HOME/.drush/cache
     - $HOME/.npm
     - campaignion_email_to_target/datasets_app/node_modules
     - campaignion_email_to_target/messages_app/node_modules
     - campaignion_wizard/redirects_app/node_modules

install:
  - export PATH="$COMPOSER_HOME/vendor/bin:$PATH"
  - composer global require drush/drush:8.1.* phpunit/phpunit:^8 torotil/upal:2.0.0-RC1
  - nvm install 10.0.0
  - npm install -g yarn

before_script:
  - repo=`pwd`
  - root=$HOME/test-root
  - mysql -e 'create database drupal'
  - php -d include_path=`pwd` -d sendmail_path=`which true` $COMPOSER_HOME/vendor/bin/drush.php --yes core-quick-drupal --core=drupal-7.69 --profile=testing --no-server --db-url=mysql://root:@127.0.0.1/drupal --root=$root
  - ln -s $repo $root/sites/all/modules/campaignion
  - cd $root
  - curl https://www.drupal.org/files/issues/1891356-drupal_static_reset-on-module-changes-30-D7.patch | patch -p1
  - drush dl --cache-duration-releasexml=0 little_helpers-2.0-alpha12
  - drush --yes pm-enable campaignion_test

script:
  - cd $repo
  - UPAL_ROOT=$root UPAL_WEB_URL=http://127.0.0.1 phpunit --bootstrap=$COMPOSER_HOME/vendor/torotil/upal/bootstrap.php --coverage-clover=coverage.xml .
  - cd $repo/campaignion_email_to_target/datasets_app
  - yarn install
  - yarn unit
  - cd $repo/campaignion_email_to_target/messages_app
  - yarn install
  - yarn unit
  - cd $repo/campaignion_wizard/redirects_app
  - yarn install
  - yarn unit

after_success:
  - bash <(curl -s https://codecov.io/bash)
