on:
  push:
    branches: [ 7.x-2.x ]
  pull_request:
    branches: [ 7.x-2.x ]

jobs:
  build:
    env:
      APP_DIRS: campaignion_email_to_target/datasets_app campaignion_email_to_target/messages_app campaignion_wizard/redirects_app
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: "Setup node"
      uses: actions/setup-node@v2
      with:
        node-version: 10
    - name: Set env
      run: |
        echo "REPO=`pwd`" >> $GITHUB_ENV
    - name: yarn install
      run: |
        for d in ${{ env.APP_DIRS }}
        do
          cd $REPO/$d
          yarn install
        done
    - name: yarn unit
      run: |
        for d in ${{ env.APP_DIRS }}
        do
          cd $REPO/$d
          yarn unit
        done
    - uses: codecov/codecov-action@v1
